### ISSUE TITLE
Can't get migrations to work.

### ISSUE THREAD

**Issue by FranciscoMessina** [romeerez/orchid-orm#13]
Hello I am just trying this project out and wanted to test it doing a Todo app with SvelteKit, but when trying to run the migrations, I don't get any output in the terminal, is there a way to have like a DEBUG mode to see what it is doing, and why there is not any output, I am pretty sure I am doing something wrong but with no error message or output it is very hard to find out what. Creating the database worked fine and dropping it as well. Is it supposed to work in SvelteKit?

**Comment by FranciscoMessina** [comment]
Mainly asking to know if this should work, if it should I would happily try to find out what is going on. If it shouldn't I will just try out in a different project.

**Comment by romeerez** [comment]
I'm sorry you get into this problem. There should be an error message, it's strange that it doesn't show up for you.

It only requires a Postgres database and should work with any framework.

Please, provide more details, it's not enough.

So you have created a database like `npm run db create` and it logged a message "Database mydb was created", right?

And then you're trying to run migrations, and it shows nothing. What migrations do you have, could you share them?

How did you configure the `db` script?

**Comment by FranciscoMessina** [comment]
So I have the standard SvelteKit project structure: 
```
my-project/
├ src/
│ ├ lib/
│ │ ├ server/
│ │ │  ├ db/ 
│ │ │  │   ├ migrations/
│ │ │  │   │       └  *timestamp*_create-user.ts
│ │ │  │   ├ base-table.ts  
│ │ │  │   └ index.ts
│ │ │  └  scripts/ 
│ │ │      └ db.ts
│ │ │
 rest of files

```
main orchid file in `src/lib/server/db/index,ts`
```typescript
import { orchidORM } from "orchid-orm";


export const db = orchidORM({
   datbaseUrl: "postgresql://postgres:postgres@localhost:5432/elrio?schema=public",
   log: true,
}, {})

```

rake db script in `src/lib/server/scripts/db.ts`
```typescript
import { appCodeUpdater } from "orchid-orm";
import { rakeDb } from "rake-db";


rakeDb({
   databaseURL: "postgresql://postgres:postgres@localhost:5432/elrio?schema=public",
}, {
   migrationsPath: '../db/migrations',
   appCodeUpdater: appCodeUpdater({
      tablePath: (tableName) => `../db/${tableName}.table.ts`,
      baseTableName: 'BaseTable',
      baseTablePath:'../db/base-table.ts',
      mainFilePath: '../db/index.ts'
   })
})
```


The one migration I created> 
```typescript

import { change } from 'rake-db';

change(async (db) => {
  await db.createTable('user', (t) => ({
      id: t.serial().primaryKey(),
      email: t.text().unique(),
      password: t.text(),
      ...t.timestamps()
  }));
});

```

**Comment by romeerez** [comment]
Thanks for the details!

It's a good issue pointing out that paths are resolved not as expected, and need to push a fix to improve this.

```ts
migrationsPath: '../db/migrations',
```

And all the rest of the paths are relative to the root of the project, not to this file.

```ts
rakeDb({
   databaseURL: "postgresql://postgres:postgres@localhost:5432/elrio?schema=public",
}, {
   migrationsPath: 'src/lib/server/db/migrations',
   appCodeUpdater: appCodeUpdater({
      tablePath: (tableName) => `src/lib/server/db/${tableName}.table.ts`,
      baseTableName: 'BaseTable',
      baseTablePath:'src/lib/server/db/base-table.ts',
      mainFilePath: 'src/lib/server/db/index.ts'
   })
})
```

This should fix the problem.

But I agree that more natural is to do it how you did, so I'll push update for this.

**Comment by FranciscoMessina** [comment]
I tried with that config at first, but ran into an [ERR_UNSUPPORTED_ESM_URL_SCHEME], then I changed it to the full path (E:/..../src/lib/server/db/migrations) but still get no output beside this: 

```bash
> orchid-orm-todo@0.0.1 db E:\Code\WebDev\orchid-orm-todo
> ts-node-esm ./src/lib/server/scripts/db.ts "migrate"
```

I have also tried using `path.resolve()` and other methods but either I get a file related error or the output above.

Maybe the issue is related to ESM vs CommonJs path resolutions?

**Comment by romeerez** [comment]
Could you try the following instead of `ts-node-esm`?

```ts
node --loader ts-node/esm ./src/lib/server/scripts/db.ts
```

Thank you for publishing reproduction repo, I'll check

**Comment by FranciscoMessina** [comment]
Still the same, depending on the path I choose it either errors out or no output.

**Comment by romeerez** [comment]
It works on my side!

I removed starting slash here /src -> src and it works!
```
migrationsPath: 'src/lib/server/db/migrations'
```

**Comment by FranciscoMessina** [comment]
Mm weird, maybe it is a Windows problem, without the starting slash I get an error.

**Comment by romeerez** [comment]
It's a separate thing, in `index.ts` you have a typo `datbaseUrl` -> `databaseURL`

Yes, that's definitely windows. Windows has slashes turned in the wrong direction, and the lib must take this into account and turn them back when accessing files, but keeping them turned right when importing.

To be fixed.

**Comment by FranciscoMessina** [comment]
Okey fixed the typo, weird that typescript didn't catch it for me.  I will keep trying to fix it , and if I get it working will update it here in case anybody else has this problem.

**Comment by romeerez** [comment]
Thank you, I'm troubleshooting this too, windows support is important. I have windows on my second laptop (not prepared for dev yet), so I'll debug it

**Comment by FranciscoMessina** [comment]
Okey so I did some digging into the source code of Rake, and I think that the problem is coming from the `config.requireTs()` call, since that's where it tries to `import()` the migration file. I changed the code in the installed package and it worked.

The change I had to make was before passing the file path to the `import()` call pass it through `pathToFileURL(path).toString()` when doing that the migrations work. Not sure if doing it that way would break it in other Operating systems.

**Comment by romeerez** [comment]
The fix is ready!

Thank you for guidance, `pathToFileURL` came useful. Plus `decodeURI` in one place.

Update deps:

```json
    "rake-db": "^2.3.21",
...
    "orchid-orm": "^1.5.20",
```

Now all paths in the rakeDb setup are relative to the file:

```ts
import { appCodeUpdater } from "orchid-orm";
import { rakeDb } from "rake-db";

rakeDb({
   databaseURL: "postgresql://postgres:postgres@localhost:5432/elrio",
}, {
   migrationsPath: '../db/migrations',
   appCodeUpdater: appCodeUpdater({
      tablePath: (tableName) => `../db/${tableName}.table.ts`,
      baseTableName: 'BaseTable',
      baseTablePath:'../db/base-table.ts',
      mainFilePath: '../db/index.ts'
   })
})
```

Tested on linux and windows. And crossed fingers for mac.

**Comment by romeerez** [comment]
Please confirm it works on your end.

**Comment by FranciscoMessina** [comment]
Yes it works! 

I also noticed some issue with the `appCodeUpdater` when updating the files to have the new tables included the path it uses to import them is wrong, it writes the absolute path trying to make it relative adding  `../`   at the start , not a big issue but uncomfortable to fix every time:

```typescript
import { BaseTable } from '..\E:\Code\WebDev\orchid-orm-todo\src\lib\server\db\base-table';

export class TestTable extends BaseTable {
  table = 'test';
  columns = this.setColumns((t) => ({
    id: t.serial().primaryKey(),
    name: t.text(),
    lastName: t.text(),
  }));
}

```

```typescript
import { orchidORM } from "orchid-orm";
import { UserTable } from './user.table';
import { TaskTable } from './task.table';
import { TestTable } from '../E:\Code\WebDev\orchid-orm-todo\src\lib\server\db\test.table';



export const db = orchidORM({
   databaseURL: "postgresql://postgres:postgres@localhost:5432/elrio?schema=public",
   log: true,
}, {
  user: UserTable,
  task: TaskTable,
  test: TestTable,
})
```

And also when resetting the DB and running migrations again, it duplicates the entries in the main `orchidORM` file, I think that a more natural way for this to work is when running the reset command delete all the Tables from the `imports` and `orchidORM` config. Or maybe check if the table it is trying to add is already there.

Later today when I get back from work I will see if I can find why the paths generated are not what I expect them to be.

**Comment by romeerez** [comment]
> And also when resetting the DB and running migrations again, it duplicates the entries in the main orchidORM file

This is fixed now, in the latest version of `rake-db` and `orchid-orm`.

```ts
import { TestTable } from '../E:\Code\WebDev\orchid-orm-todo\src\lib\server\db\test.table';
```

I'm going to jump into this later today or tomorrow.

**Comment by romeerez** [comment]
Now resolved the relative path on windows issue! Please check when you have time.

**Comment by FranciscoMessina** [comment]
It works! Great job, thank you for the quick fixes! I am closing this issue since I think everything related to it was fixed for now. Would you consider opening a discord server for this package? To start building a community there?

**Comment by romeerez** [comment]
@FranciscoMessina welcome to discord: https://discord.gg/M7bYBArb

**Comment by romeerez** [comment]
It is a fresh empty server for now, need to figure out how all of those bells in whistles works here

**Comment by manifreaky** [comment]
there is still a problem on my system when running migrations

the function pathToFileURL 
`await config.import(url.pathToFileURL(file.path).pathname);`

adds a slash to the beginning of the path and it looks like this:

` /C:/Users/.../src/db/migrations/20230214072400_createUser.ts`

When i remove the call to the function and just use file.path it works

**Comment by romeerez** [comment]
Thank you for pointing this out and suggesting the fix. I published the fix for it in rake-db 2.3.36, should work now.

I'll do some more testing later before closing this.

**Comment by romeerez** [comment]
Finally tested this on Windows, and added one more crutch for this, seems to be working with and without ESM.
