### ISSUE TITLE
default empty array values & creating migration

### ISSUE THREAD

**Issue by krishna-404** [romeerez/orchid-orm#390]
Here is one of the column definitions in the schema `styles: t.array(t.string()).default([]),`

Creating migration on adding of the above column definition is throwing the below error
```
Error.captureStackTrace(err)
│                 ^
│ 
│ error: cannot determine type of empty array
│     at /Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pg@8.12.0/node_module
│ s/pg/lib/client.js:526:17
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│     at TransactionAdapter.arrays (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/
│ .pnpm/pqb@0.40.0/node_modules/pqb/src/adapter.ts:249:12)
│     at changeTable (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/rake-db@
│ 2.22.33/node_modules/rake-db/src/migration/changeTable.ts:358:20)
│     at async eval (eval at verifyMigration (/Users/krishna404/codeProjects/teziapp/zeon/nod
│ e_modules/.pnpm/orchid-orm@1.35.5_typescript@5.5.4/node_modules/orchid-orm/dist/migrations.
│ js:2100:23), <anonymous>:5:3)
│     at adapter.transaction.text (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.
│ pnpm/orchid-orm@1.35.5_typescript@5.5.4/node_modules/orchid-orm/src/migrations/generate/ver
│ ifyMigration.ts:40:15)
│     at Adapter.transaction (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/
│ pqb@0.40.0/node_modules/pqb/src/adapter.ts:142:18)
│     at generate (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/orchid-orm@
│ 1.35.5_typescript@5.5.4/node_modules/orchid-orm/src/migrations/generate/generate.ts:122:20)
│     at runCommand (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/rake-db@2
│ .22.33/node_modules/rake-db/src/rakeDb.ts:155:11) {
│   length: 174,
│   severity: 'ERROR',
│   code: '42P18',
│   detail: undefined,
│   hint: 'Explicitly cast to the desired type, for example ARRAY[]::integer[].',
│   position: undefined,
│   internalPosition: undefined,
│   internalQuery: undefined,
│   where: undefined,
│   schema: undefined,
│   table: undefined,
│   column: undefined,
│   dataType: undefined,
│   constraint: undefined,
│   file: 'parse_expr.c',
│   line: '2026',
│   routine: 'transformArrayExpr'
│ }
│ 
│ Node.js v20.10.0
```

**Comment by IlyaSemenov** [comment]
Just in case, the workaround is raw SQL:

```ts
const { sql } = BaseTable

change(async (db) => {
  await db.createTable("tmp", t => ({
    id: t.serial().primaryKey(),
    styles: t.array(t.string()).default(sql`array[]::varchar[]`),
  }))
})
```

**Comment by krishna-404** [comment]
Also I am facing this issue when trying to access a null column. The error isnt consistent though.

```
Error in tRPC handler on path 'me.persona': TypeError: Cannot read properties of null (reading '
│ 0')
│     at parsePostgresArray (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.
│ 40.0/node_modules/pqb/src/columns/array.ts:136:7)
│     ... 4 lines matching cause stack trace ...
│     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
│   code: 'INTERNAL_SERVER_ERROR',
│   name: 'TRPCError',
│   [cause]: TypeError: Cannot read properties of null (reading '0')
│       at parsePostgresArray (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@
│ 0.40.0/node_modules/pqb/src/columns/array.ts:136:7)
│       at Object.ArrayColumn.parseFn.Object.assign.hideFromCode [as interests] (/Users/krishna404
│ /codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/columns/array.ts:1
│ 16:7)
│       at parseRecord (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/
│ node_modules/pqb/src/queryMethods/then.ts:591:49)
│       at Object.handleResult (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb
│ @0.40.0/node_modules/pqb/src/queryMethods/then.ts:493:32)
│       at then (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_mo
│ dules/pqb/src/queryMethods/then.ts:237:22)
│       at processTicksAndRejections (node:internal/process/task_queues:95:5) {
│     cause: Error
│         at Db.getThen (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0
│ /node_modules/pqb/src/queryMethods/then.ts:84:18)
│         at /Users/krishna404/codeProjects/teziapp/zeon/apps/api/src/controllers/me.controller.ts
│ :7:71
│         at resolveMiddleware (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@tr
│ pc+server@11.0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuil
│ der.js:104:36)
│         at callRecursive (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+s
│ erver@11.0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.
│ js:154:38)
│         at next (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+server@11.
│ 0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.js:163:32
│ )
│         at /Users/krishna404/codeProjects/teziapp/zeon/apps/api/src/context.trpc.ts:64:11
│         at callRecursive (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+s
│ erver@11.0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.
│ js:154:38)
│         at procedure (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+serve
│ r@11.0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.js:1
│ 84:30)
│         at /Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+server@11.0.0-rc
│ .421/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.js:196:36
│         at Array.map (<anonymous>)
│   }
│ }
```

**Comment by romeerez** [comment]
For the second problem of parsing a null value for array, I published a fix already yesterday.

**Comment by romeerez** [comment]
I published a fix, now empty arrays should be handled properly in column defaults.

**Comment by krishna-404** [comment]
still getting array when creating migration

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/2ed01338-d00e-4980-b371-6f5bdd13e071">

**Comment by krishna-404** [comment]
@romeerez

**Comment by romeerez** [comment]
@krishna-404 could you share your migration code?

**Comment by krishna-404** [comment]
was facing this issue when creating migration. This is what my schema looked like

```
focus: t.array(t.string()).default([]),
interests: t.array(t.string()).default([]),
styles: t.array(t.string()).default([]),
```

**Comment by IlyaSemenov** [comment]
I was actually hit by the same:

```ts
    await db.changeTable("user", t => ({
      links: t.array(t.varchar()).default([]),
    }))
```

```
 ERROR  (0.8ms) ALTER TABLE "user"
  ADD COLUMN "links" varchar[] NOT NULL DEFAULT {} Error: syntax error at or near "{"
```

**Comment by romeerez** [comment]
I published a fix, should be fine.

**Comment by krishna-404** [comment]
Hi @romeerez looks like this is still persisting. I just tried in `v1.3.7.4` & I am getting the below error during migration

My schema def is `t.array(t.string()).default([])`
earlier it was working with `.nullable().default(null)`, now its working with that.

Also the issue is not happening during creation of table, but when I am trying to insert values into the table during migration. Thanks!

Also 
```
api:db:     validateArray(time, 'time');
api:db:     ^
api:db: 
api:db: TypeError [ERR_INVALID_ARG_TYPE]: The "time" argument must be an instance of Array. Received type boolean (false)
api:db:     at process.hrtime (node:internal/process/per_thread:74:5)
api:db:     at makeMessage (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.42.3/node_modules/pqb/src/queryMethods/log.ts:19:27)
api:db:     at Object.onError (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.42.3/node_modules/pqb/src/queryMethods/log.ts:66:14)
api:db:     at wrapWithLog (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/rake-db@2.23.11/node_modules/rake-db/src/migration/migration.ts:1433:11)
api:db:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api:db:     at async then (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.42api:db: modules/pqb/src/queryMethods/then.ts:222:22) {
api:db:   code: 'ERR_INVALID_ARG_TYPE',
api:db:   cause: Error
api:db:       at Array.<anonymous> (/Users/krishna404/codeProjects/teziapp/zeon/apps/api/src/db/migrations/0010_li-posts-seperate-table.ts:238:4)
api:db:       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api:db:       at async runMigration (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/rake-db@2.23.11/node_modules/rake-db/src/commands/migrateOrRollback.ts:396:7)
api:db:       at async migrateOrRollback (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/rake-db@2.23.11/node_modules/rake-db/src/commands/migrateOrRollback.ts:290:5)
api:db:       at async <anonymous> (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/rake-db@2.23.11/node_modules/rake-db/src/commands/migrateOrRollback.ts:100:24)
api:db:       at async Adapter.transaction (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.42.3/node_modules/pqb/src/adapter.ts:142:18)
api:db:       at async <anonymous> (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/rake-db@2.23.11/node_modules/rake-db/src/commands/migrateOrRollback.ts:92:15)
api:db:       at async runCommand (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/rake-db@2.23.11/node_modules/rake-db/src/rakeDb.ts:155:11)
```

**Comment by krishna-404** [comment]
So I used raw sql query to push data into the table. I am now facing below error when trying to query the table.

```
"message": "Cannot read properties of null (reading '0'): Cannot read properties of null (reading '0'): ",
api:dev:       "stack":
api:dev:           TypeError: Cannot read properties of null (reading '0')
api:dev:               at parsePostgresArray (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/columns/array.ts:136:7)
api:dev:               at Object.ArrayColumn.parseFn.Object.assign.hideFromCode [as embedded_links] (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/columns/array.ts:116:7)
api:dev:               at parseRecord (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:591:49)
api:dev:               at Object.handleResult (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/papi:dev: /node_modules/pqb/src/queryMethods/then.ts:493:32)
api:dev:               at then (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:237:22)
api:dev:               at processTicksAndRejections (node:internal/process/task_queues:95:5)
api:dev:           caused by: TypeError: Cannot read properties of null (reading '0')
api:dev:               at parsePostgresArray (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/columns/array.ts:136:7)
api:dev:               at Object.ArrayColumn.parseFn.Object.assign.hideFromCode [as embedded_links] (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/columns/array.ts:116:7)
api:dev:               at parseRecord (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:591:49)
api:dev:               at Object.handleResult (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:493:32)
api:dev:               at then (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:237:22)
api:dev:               at processTicksAndRejections (node:internal/process/task_queues:95:5)
api:dev:           caused by: Error
api:dev:               at Db.getThen (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/pqb@0.40.0/node_modules/pqb/src/queryMethods/then.ts:84:18)
api:dev:               at /Users/krishna404/codeProjects/teziapp/zeon/apps/api/src/controllers/linkedin.controller.ts:77:34
api:dev:               at processTicksAndRejections (node:internal/process/task_queues:95:5)
api:dev:               at async resolveMiddleware (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+server@11.0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.js:104:30)
api:dev:               at async callRecursive (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+server@11.0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.js:154:32)
api:dev:               at async callRecursive (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+server@11.0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.js:154:32)
api:dev:               at async procedure (/Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+server@11.0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.js:184:24)
api:dev:               at async /Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+server@11.0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.js:196:30
api:dev:               at async /Users/krishna404/codeProjects/teziapp/zeon/node_modules/.pnpm/@trpc+server@11.0.0-rc.421/node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.js:336:45
api:dev:       "code": "INTERNAL_SERVER_ERROR",
```

**Comment by IlyaSemenov** [comment]
I don't concur. `t.array(t.varchar()).default([])` works fine with orchid-orm 1.36.1 + pqb 0.41.1:

```
  "links" varchar[] NOT NULL DEFAULT '{}'
```

I can see that your second trace uses pqb@0.40.0, please make double sure you've upgraded properly.

**Comment by krishna-404** [comment]
> I can see that your second trace uses pqb@0.40.0, please make double sure you've upgraded properly.

Is there any way the orchid can force the correct internal dependencies? Atleast show correct error & solution paths?

In this particular case the error when query was due to columns having `null` values in `string[]` type columns. In schema definition its marked as `nullable`. Once I populated all the null values with an empty array, the errors during querying went away.

I'll now try with correct dependencies & report back here.

**Comment by krishna-404** [comment]
As soon as I upgrade... typescript goes crazy for some reason... right now I am working on `v1.35.5`

<img width="372" alt="image" src="https://github.com/user-attachments/assets/13cf50a3-69dc-4043-b212-3b43619b3024">

**Comment by romeerez** [comment]
This seems to be alright on my end.

Previously, you had to install `orchid-orm`, `pqb`, `rake-db` all independently, and it was causing problems constantly when updating one but not another.

So I included `pqb` and `rake-db` into `orchid-orm`, so you only need to install this one library, and the rest are installed internally, with correct versions.

Other libraries that you might be using still may depend on `pqb` and cause incompatibilities: `orchid-orm-test-factories`, `orchid-orm-schema-to-zod`, so when updating `orchid-orm` you also should update all the rest.

> typescript goes crazy for some reason

If all seems fine in the package.json but TS is still confused, re-opening the editor helps.
