### ISSUE TITLE
[RakeDB] expressions property ignored when creating indexes

### ISSUE THREAD

**Issue by matthewmorek** [romeerez/orchid-orm#476]
It looks like RakeDB currently ignores `expression` property when creating custom indexes:
```ts
import { change } from '../dbScript'

change(async (db) => {
  await db.createSchema('extensions')

  await db.createExtension('extensions.vector', {
    version: '0.8.0',
  })
  
  await db.createTable('documents', (t) => ({
    id: t.bigint().primaryKey().foreignKey('questions', 'id'),
    content: t.text().nullable(),
    metadata: t.json().nullable(),
    embedding: t.type('extensions.vector').nullable().index({
      opclass: '"extensions"."vector_l2_ops"',
      using: 'hnsw',
      expression: '(embedding::vector(4))',
    }),
  }))
})
```
This is supposed to produce something like the following query:
```sql
CREATE INDEX "documents_embedding_idx" ON "public"."documents"
  USING hnsw ((embedding::vector(4)) "extensions"."vector_l2_ops");
```
Instead, the query produced by RakeDB is as such:
```sql
CREATE INDEX "documents_embedding_idx" ON "documents" USING hnsw ("embedding" "extensions"."vector_l2_ops");
```
which results in an error:
```
Error: column does not have dimensions
```

#### Versions
```
OrchidORM:  1.42.4
RakeDB:     2.23.37
pg:         8.14.1
Node.js:    22.14.0
```

**Comment by romeerez** [comment]
Thanks for catching, I published a fix.

**Comment by matthewmorek** [comment]
Looks like this issue is still present for the exact same schema, just in a different way. Does Orchid do any cleanup on the `expression` property? It surely looks that way, but it should be treated like raw SQL (according to the docs).

## Migration code
```ts
    embedding: t.type('extensions.vector').nullable().index({
      opclass: 'extensions.vector_l2_ops',
      using: 'hnsw',
      expression: 'embedding::"extensions".vector (128)',
    })
```

## Expected output
```sql
CREATE INDEX "documents_embedding_idx" ON "documents" USING hnsw (((embedding::"extensions".vector (128))) "extensions"."vector_l2_ops");
--- OK: CREATE INDEX
```

## Orchid output
```sql
CREATE INDEX "documents_embedding_idx" ON "documents" USING hnsw (((embedding::vector(128))) "extensions"."vector_l2_ops")
--- Error: type "vector" does not exist
```
This error happens because the `extensions` schema prefix was omitted from the generated query, while it was explicitly used in the expression.

I confirmed this manually in SQL console using the following code:
```sql
CREATE SCHEMA "extensions";
CREATE EXTENSION "vector" SCHEMA "extensions" VERSION '0.8.0';
CREATE TABLE "documents" (
  "id" int8 PRIMARY KEY,
  "content" text NOT NULL,
  "metadata" jsonb NOT NULL,
  "embedding" "extensions".vector
);
CREATE INDEX "documents_embedding_idx" ON "documents" USING hnsw (((embedding::"extensions".vector (128))) "extensions"."vector_l2_ops");
```

**Comment by matthewmorek** [comment]
Turns out this was caused by a recurrent migration trying to use vector function without a prefix. Orchid does produce the correct query expression after all. My apologies about the noise!
