### ISSUE TITLE
Migration generator fails to verify when using raw SQL

### ISSUE THREAD

**Issue by mordechaim** [romeerez/orchid-orm#590]
> Now, since I updated past 1.57.7 the migration gen fails for me with tons of code not being verified. 
> 
> The common denominator on all those unverified code is they all use raw sql:
> - Column checks
> - Index with a `where`
> 
> When reading the failed verification it seems like the casing don't match (I always use all lowercase) and it adds type casting.
> 
> For example:
> 
> ```ts
>   await db.changeTable('employee_rate', (t) => ({
>     ...t.drop(
>       t.check(t.sql`((facility_id IS NOT NULL) OR (bill_rate IS NULL))`, 'employee_rate_check')
>     ),
>     ...t.add(
>       t.check(t.sql`"facility_id" is not null or "bill_rate" is null`, 'employee_rate_check')
>     ),
>   }));
> ```
> 
> And
> 
> ```ts
>   await db.changeTable('employee', (t) => ({
>     ...t.drop(
>       t.index(['deleted'], {
>         where: '(deleted IS NULL)',
>       })
>     ),
>     ...t.add(
>       t.index(['deleted'], {
>         where: '"deleted" is null',
>       })
>     ),
>     ...t.drop(
>       t.check(t.sql`(phone ~ '^[0-9]{3}-[0-9]{3}-[0-9]{4}(:? x[0-9]{1,6})?$'::text)`, 'employee_phone_format_check')
>     ),
>     ...t.add(
>       t.check(t.sql`phone ~ '^[0-9]{3}-[0-9]{3}-[0-9]{4}(:? x[0-9]{1,6})?$'`, 'employee_phone_format_check')
>     )
> })); 

 _Originally posted by @mordechaim in [#583](https://github.com/romeerez/orchid-orm/issues/583#issuecomment-3481711342)_

I want to add: These aren't new changes. I have a clean diff, simply updated Orchid.

**Comment by romeerez** [comment]
I even updated from Postgres 17 to 18 to see if it makes a difference - no, still can't reproduce.

**Comment by romeerez** [comment]
@mordechaim I'll fix the case that you made a reproduction for, but that seems to be a minor problem - recreating index.

> drops and adds the deleted column with different casing.

For me it generates dropping and adding only the index, not the column:
```ts
await db.changeTable('one', (t) => ({
  enum: t.add(t.enum('public.enum_name')),
  ...t.drop(
    t.index(['deleted'], {
      where: '(deleted IS NULL)',
    })
  ),
  ...t.add(
    t.index(['deleted'], {
      where: '"deleted" is null',
    })
  ),
}));
```

Any updates on the original problem?

I tried to compare changes between 1.57 and 1.55 but it's doomed without knowing what exactly am I looking for.

**Comment by mordechaim** [comment]
There seems to be a commit (https://github.com/romeerez/orchid-orm/commit/4bc4d085a3134de4b192055020494fe92d74aff1) that deals with enums. So it's very likely somehow related.

**Comment by romeerez** [comment]
Thank you for finding it!

Knowing that it's caused by the geography type, it should be straightforward to fix.

I'll add a debug option for logging in that case.

**Comment by romeerez** [comment]
@mordechaim I published a fix for this, let me know if it helps or not, it's possible there's something else.

>  A crash in the query is most certainly a bug which needs attention.

Not quite, "type does not exist" error can mean that you're adding a new type in the same migration.

Like, a new enum: you're adding a new enum, and there is an index with `where` condition that depends on it, or a database check. Or even with this `georgaphy` type, if you enable postgis at the same time as having index `where` that depends on that type, it's not yet available.

Ideally, I'd have to somehow rewrite the logic to make sure that indexes, checks, and such are only executed after migrating everything else. But that's too complex and that's why I'm ignoring the "type doesn't exist" errors in this case.

Previously it was ignoring all sorts of errors, which isn't good, but invalid SQL would fail anyway, and now changing that to only ignore "type does not exist" errors.

**Comment by romeerez** [comment]
Indeed, thank you, I'll fix the array case as well.

**Comment by romeerez** [comment]
I pushed a fix to also properly handle array types when having such custom SQLs for indexes and other cases.

**Comment by mordechaim** [comment]
Tried it, getting this error (using postgres-js, but same error on node-postgres)

```
PostgresError: ROLLBACK TO SAVEPOINT can only be used in transaction blocks
```

**Comment by mordechaim** [comment]
I tried version 1.58.6 (which doesn't have this SAVEPOINT logic, but also doesn't deal with arrays yet). It crashed as expected, but the error is completely not helpful in any way:

```
error: current transaction is aborted, commands ignored until end of transaction block
```

Can we get the actual pg error? This will make reporting an issue much easier.


--------------

Actually, this is only happening on node-postgres. In postgres-js we get a nice error message:

```
PostgresError: type "citext[]" does not exist
```

**Comment by romeerez** [comment]
> error: current transaction is aborted, commands ignored until end of transaction block

This is fixed by the savepoints, so please try the latest version.
"commands ignored" because transaction failed, save points do the recovering.

> PostgresError: type "citext[]" does not exist

Great, so hopefully it's going to work with the last update for array handling!

**Comment by mordechaim** [comment]
> This is fixed by the savepoints, so please try the latest version.

But I tried and it fails with the error I posted earlier

**Comment by romeerez** [comment]
But you said that you didn't try the fix:

> I tried version 1.58.6 (which doesn't have this SAVEPOINT logic, but also doesn't deal with arrays yet)

**Comment by romeerez** [comment]
@mordechaim apologies for the fix to take long!

I published a fix, 1.58.9 works fine in your reproduction repo, I'm sure this problem related to arrays/enums/types conflicting with SQLs in indexes is solved now.

**Comment by mordechaim** [comment]
Unfortunately this error persists (in both node-pg and pg.js):

```
PostgresError: ROLLBACK TO SAVEPOINT can only be used in transaction blocks
```

Manually patching and removing this LOC fixes it:

```ts
await adapter.query(`ROLLBACK TO SAVEPOINT "${viewName}"`);
```

**Comment by romeerez** [comment]
> Unfortunately this error persists (in both node-pg and pg.js):
> PostgresError: ROLLBACK TO SAVEPOINT can only be used in transaction blocks
> Manually patching and removing this LOC fixes it:

But how, if I installed 1.58.9 after publishing, tested it. I had this problem in 1.58.8, published a fix in 1.58.9, it worked.

It is impossible from the code perspective. [Here in this change](https://github.com/romeerez/orchid-orm/commit/16ae87ab5d900c0f4dd7e037fdaa3892660f6b7b#diff-5889943f5f7ab90762910d8ba04ac47ce6a867258489c1033a81dfa1e66d4e39R229-R232) you can see that the savepoint argument is ignored in the `query` function that is on a regular Postgres client, it's only used in that file below on a transactional client.

Please double-check if that's 1.58.9, perhaps it didn't update due to some caching.

**Comment by romeerez** [comment]
> pay_overtime and bill_overtime are enums too, and they too are NULL::text unquoted.

This is easy to fix. I assumed that all enums are text-compatible and it's just easier to use the `text` type instead, apparently it was a mistake.

**Comment by mordechaim** [comment]
> It is impossible from the code perspective.

It's this line that fails:

https://github.com/romeerez/orchid-orm/blob/85c6b2591c52ad4644ac1a8beec019a92f0dc808/packages/orm/src/migrations/generate/generators/generators.utils.ts#L52

**Comment by romeerez** [comment]
> Maybe you can just stick to text type and not cast this:

There are two selects in that view: "inDB" and "inCode". The cast is only on the "inDB" side, which means the cast `'provider'::clock_method` is automatically added by Postgres itself when it returns the current SQL for that case.

Anyhow, I published a new fix in **1.58.10**, please check. Thank you for pointing to that savepoint line - it was a leftover.

Now the enum type will be used as is, not a `text` as it was previously. Should be fine.
